# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: cloud.google.com/v1
kind: ComputeClass
metadata:
  name: gpu-g4-180gb-s48-x1
spec:
  activeMigration:
    optimizeRulePriority: true
  nodePoolConfig:
    imageStreaming:
      enabled: true
  nodePoolAutoCreation:
    enabled: true
  priorities:
    # Use a specific reservation
    # - gpu:
    #     count: 1
    #     driverVersion: latest
    #     type: nvidia-rtx-pro-6000
    #   machineType: g4-standard-48
    #   maxPodsPerNode: 32
    #   reservations:
    #     affinity: Specific
    #     specific:
    #       - name: nvidia-rtx-pro-6000-specific
    #         reservationBlock:
    #           name: <RESERVATION_NAME>
    #   spot: false

    # Use any reservation
    - gpu:
        count: 1
        driverVersion: latest
        type: nvidia-rtx-pro-6000
      machineType: g4-standard-48
      maxPodsPerNode: 32
      reservations:
        affinity: AnyBestEffort
      spot: false

    # Use on-demand
    - gpu:
        count: 1
        driverVersion: latest
        type: nvidia-rtx-pro-6000
      machineType: g4-standard-48
      maxPodsPerNode: 32
      spot: false
    # Use spot
    - gpu:
        count: 1
        driverVersion: latest
        type: nvidia-rtx-pro-6000
      machineType: g4-standard-48
      maxPodsPerNode: 32
      spot: true
