# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
image:
  repository: rayproject/ray
  tag: 2.40.0-py312-gpu
  pullPolicy: IfNotPresent

nameOverride: kuberay

head:
  groupName: headgroup
  rayVersion: 2.40.0
  enableInTreeAutoscaling: true
  serviceAccountName: ${ray_head_kubernetes_service_account}
  rayStartParams:
    dashboard-host: "0.0.0.0"
    block: "true"
    num-cpus: "0" # Prevent tasks from begins scheduled on the head
  image:
    repository: rayproject/ray
    tag: 2.40.0-py312
    pullPolicy: IfNotPresent
  containerEnv:
    - name: RAY_memory_monitor_refresh_ms
      value: "0"
  resources:
    limits:
      cpu: "4"
      memory: 10G
      ephemeral-storage: 20Gi
    requests:
      cpu: "4"
      memory: 10G
      ephemeral-storage: 10Gi
  nodeSelector:
    iam.gke.io/gke-metadata-server-enabled: "true"
  tolerations: []

worker:
  groupName: cpu-n4x2
  replicas: 0
  minReplicas: 0
  maxReplicas: 16
  type: worker
  serviceAccountName: ${ray_worker_kubernetes_service_account}
  rayStartParams:
    block: "true"
    resources: '"{\"cpu\": 2}"'
  initContainerImage: busybox:1.28
  resources:
    limits:
      cpu: 2
      memory: "4G"
    requests:
      cpu: 2
      memory: "4G"
  nodeSelector: {}
  tolerations: []

additionalWorkerGroups:
  gpul4x2:
    minReplicas: 0
    maxReplicas: 3
    replicas: 0
    serviceAccountName: ${ray_worker_kubernetes_service_account}
    type: worker
    rayStartParams:
      block: "true"
      resources: '"{\"l4_gpu\": 2}"'
    initContainerImage: "busybox:1.28"
    resources:
      limits:
        cpu: "22"
        nvidia.com/gpu: "2"
        memory: "90G"
        ephemeral-storage: 20Gi
      requests:
        cpu: "22"
        nvidia.com/gpu: "2"
        memory: "90G"
        ephemeral-storage: 10Gi
    nodeSelector:
      iam.gke.io/gke-metadata-server-enabled: "true"
      cloud.google.com/gke-accelerator: "nvidia-l4"
    tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"

service:
  type: ClusterIP
