---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - envs:
      - runtime.env
    name: runtime
    namespace: replaced-by-kustomize

nameSuffix: -vllm

patches:
  - path: patch-load.yaml
  - path: patch-data.yaml