# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - envs:
      - runtime.env
    name: runtime
    namespace: replaced-by-kustomize

nameSuffix: -rtx-pro-6000-llama-3-3-70b-instruct-sd-ngram

patches:
  - path: patch-resources.yaml
  - path: patch-nodeselector.yaml
  - target:
      kind: Deployment
      name: vllm
    path: patch-spec-decoding.yaml

replacements:
  - source:
      fieldPath: data.APP_LABEL
      kind: ConfigMap
      name: runtime
    targets:
      - fieldPaths:
          - spec.selector.matchLabels.app
          - spec.template.metadata.labels.app
        select:
          kind: Deployment
      - fieldPaths:
          - spec.selector.app
        select:
          kind: Service
  - source:
      fieldPath: data.CONTAINER_IMAGE_URL
      kind: ConfigMap
      name: vllm
    targets:
      - fieldPaths:
          - spec.template.spec.containers.[name=inference-server].image
        select:
          kind: Deployment
  - source:
      fieldPath: data.INFERENCE_KUBERNETES_NAMESPACE
      kind: ConfigMap
      name: deployment
    targets:
      - fieldPaths:
          - metadata.namespace
        select:
          kind: ConfigMap
      - fieldPaths:
          - metadata.namespace
        select:
          kind: Deployment
      - fieldPaths:
          - metadata.namespace
        select:
          kind: Service
      - fieldPaths:
          - metadata.namespace
        select:
          kind: ServiceAccount
  - source:
      fieldPath: data.INFERENCE_KUBERNETES_SERVICE_ACCOUNT
      kind: ConfigMap
      name: deployment
    targets:
      - fieldPaths:
          - spec.template.spec.serviceAccountName
        select:
          kind: Deployment
      - fieldPaths:
          - metadata.name
        select:
          kind: ServiceAccount
  - source:
      fieldPath: data.MODEL_BUCKET_NAME
      kind: ConfigMap
      name: deployment
    targets:
      - fieldPaths:
          - spec.template.spec.volumes.[name=huggingface-hub-model-bucket].csi.volumeAttributes.bucketName
        options:
          delimiter: .
          index: 0
        select:
          kind: Deployment
  - source:
      fieldPath: data.MODEL_NAME
      kind: ConfigMap
      name: runtime
    targets:
      - fieldPaths:
          - spec.template.metadata.labels.[ai.gke.io/model]
        select:
          kind: Deployment

resources:
  - ../base
